name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpulse-dev libx11-dev libxft-dev libcjson-dev libbluetooth-dev libfreetype6-dev i3-wm libxrandr-dev xserver-xorg-dev libxinerama-dev
    
    - name: Initialize submodules
      run: git submodule update --init --recursive
      
    - name: make
      run: ./build.sh

    - name: make debug
      run: ./build.sh debug
